### ISSUE TITLE
 The reply URL specified in the request does not match the reply URLs configured for the application

### ISSUE THREAD

**Issue by crouinicrouina** [OfficeDev/office-add-in-saas-monetization-sample#1]
Hello everyone,

First of all, I'd like to thank you guys for this code sample repository, it is very useful !

*Context* : I'm in charge of developing a SaaS offering for two brand new Excel add-ins. We already developed them. We are now at the monetization step.

I'm currently trying to replicate the tutorial from this repository. I managed to deploy the Mock WebAPI, Web App, AppSource and the Outlook Addin on Azure successfully. However, **I'm stuck at the Testing step**. I guess I did something wrong in the configuration, yet, sadly, I can't find/debug my mistake :(

As I follow along the documentation from this repo, I'm facing an issue when trying to connect to the MockAppSource for the first time. I attached two screenshots below :

- the first one with the first login error : **Sorry, but we’re having trouble signing you in.
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'c9e36b1f-f193-40b0-92b6-3c383c7bba27'.**

- the second one, with the Mock App Source redirect URIs setup : `https://localhost:44381/` and `https://localhost:44381/signin-oidc`

*Mock App Source First Login Error* :

![MockAppSouceError](https://user-images.githubusercontent.com/60365279/77677013-65f84f80-6f8f-11ea-8558-dbc34dad7259.png)

*Mock App Source Redirect URIs Setup* :

![MockAppSourceRedirectURIs](https://user-images.githubusercontent.com/60365279/77677028-6bee3080-6f8f-11ea-8286-e4baed8e9910.png)
)

Here's the link of the MockAppSource I published if it can help : https://contosomonetizationoutlookaddin-cc1c-test3.azurewebsites.net/

Thanks for your help in advance !

**Comment by crouinicrouina** [comment]
Additionnal information : as I added both these redirect URIs, I managed to login in the AppSource 

![Screenshot from 2020-03-27 12-38-33](https://user-images.githubusercontent.com/60365279/77752581-1ca80e80-7028-11ea-9b28-eaf5d779adec.png)

Is it what I was supposed to do in the first place ?

**Comment by TBag** [comment]
Hello,

It appears that the UpdateApps.ps1 Powershell script may have failed to run for you.  The script updates the redirect URLs.  Please try upgrading the Microsoft Graph PowerShell SDK Preview to the latest version and running the UpdateApps.ps1 PowerShell Script again.  It will update the redirect URLs with the correct values.

**Comment by crouinicrouina** [comment]
Hello Todd,

thank you for getting back to me. 

I thought that I had to run the UpdateApps.ps1 script in case I wanted to update my app (i.e: not on first deployment). 

As I ran the UpdateApps.ps1, script, the URLs indeed updated successfully.

Thanks!

**Comment by TBag** [comment]
You're welcome.  Glad to hear it's all sorted out.
